### ISSUE TITLE
Request to add HTTP/SOCKS5 forward proxy for Orbot//为Orbot增加HTTP/SOCKS5前置代理的请求

### ISSUE THREAD

**Issue by FeynmanWong** [guardianproject/orbot#1004]
Hi, I'm currently living in mainland China, which causes me to use Orbot and find that it can't connect to TOR using Chinese networks (including using obfs and Snowflake), which is always frustrating for me ---- as I'm used to transfer all my data via tor, including emails, instant messaging software, web browsers, etc.
Hi，我目前居住在中国大陆，这导致我使用Orbot时，发现它无法用中国的网络连接到TOR（包括使用obfs和Snowflake），这让我总是很沮丧----因为我习惯于将我的所有数据通过tor传输，包括邮件、即时通信软件、网页浏览器等。

One possible solution is to add support for forward proxies. For example, using a SOCKS5 or HTTP proxy to connect to Tor instead of a bridge for the purpose of using a global vpn - in fact, many vpn's that can be used in China can be set up with a SOCKS proxy without having to start the vpn.
一个可能的解决方案是，增加对于前置代理的支持。例如使用SOCKS5或者HTTP代理来代替网桥连接Tor，以此实现使用全局vpn的目的---实际上，很多可以在中国使用的vpn都可以设置SOCKS代理而不必启动vpn。

Hopefully this strange need can be met.
希望这个奇怪的需求可以得到满足。

**Comment by n8fr8** [comment]
Thank you for your very helpful report!

There is already support for this in the Orbot settings. Please look for the proxy settings values there and let us know if they can work for you.

Otherwise, the latest BETA release on Github has improvements for bridge access:
https://github.com/guardianproject/orbot/releases/tag/17.1.1-BETA-2-tor-0.4.8.7
