### ISSUE TITLE
Improve apps VPN selection UI

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#116]
Currently, the app selection UI for the VPN feature is just a long listed in alphabetical order, sorted by whether an app has been selected or not. 

We should be able to display grouping of apps, based on the most common ones people might want to send through Tor (WhatsApp, Twitter, Facebook), or based on types of apps (messaging, browser, email, etc). 

Ultimately, we want to make it easier for users to quickly find the apps they might need to send through Tor.

**Comment by bitmold** [comment]
Hi!! I'd be more than happy to work on this enhancement. 

I've actually started to tweak the UI of that screen in general, the apps in the GridView aren't centered and the TextView for an app's name tends to overflow and cover up a neighboring app's TextView. 

I'll start by working on these layout tweaks and then I'll go in the direction you presented in this issue

**Comment by bitmold** [comment]
I've opened a PR with the layout adjustments [over here]

**Comment by bitmold** [comment]
What exactly is the deliverable for this ticket? I don't think it would be worthwhile to add some sort of app grouping feature because we'd essentially be hardcoding in many dozen APK package names we deem are popular. Different users in different parts of the world may or may not have their own popular software that could fall outside of our list which ultimately I think could lead to more confusion than just having the apps sorted out by name as it is down right now
