### ISSUE TITLE
VPN Mode App Selection View

### ISSUE THREAD

**Issue by vindicatorr** [guardianproject/orbot#145]
Android 4.4.2
I don't seem to be able to get my apps to make use of orbots vpn.

When I start orbot fresh, I get the intro which allows me to selects the apps, but when I start VPN Mode manually, the screen flashes once quickly like it's trying to show me the selection view but doesn't.

There is no view to allow for app selection other than starting fresh and going through the intro screen, but even that doesn't appear to get the browser to make use of the vpn.

**Comment by alirezaimi** [comment]
same ...

**Comment by bitmold** [comment]
This ticket is dated, I believe the fact that @vindicatorr was ever able to see the app selection screen was because of a bug in Orbot that has since been resolved in the interim. 

Android `VPNService`s can only allow per-app filtering on Android 5 Lollipop (API 21) or higher. On older versions of Orbot (we support APIs 16-20 you can still use Orbot as a VPN but it will be for all of the traffic on your device
