### ISSUE TITLE
How to route all traffic to another android device?

### ISSUE THREAD

**Issue by noman720** [guardianproject/orbot#148]
Is there any way to route all traffic to another android device in the same network? Just to observe traffic by another android device.

**Comment by ilovelinux** [comment]
Can you give us a better explaination of what you are trying to do?
It's something like: Smartphone 1 -> Smartphone 2 (with tor?) -> Network ?

**Comment by pgerber** [comment]
If I had to route traffic through another Android device, I guess I'd setup a Wi-Fi hotspot. Is there a particular reason the traffic needs to be observed on a second Android device. Could it be observed on the same device or perhaps by a non-Android device?

Since you posted this on Orbot's issue tracker, I wonder how it is supposed to be involved here. Is the device in the middle supposed to send the traffic over Tor? If so, note that Tor supports TCP only.
