### ISSUE TITLE
Orbot's VPN is not followed by apps (Android 8.1)

### ISSUE THREAD

**Issue by Pant** [guardianproject/orbot#162]
I installed orbot from ​[https://github.com/n8fr8/orbot/releases](https://github.com/n8fr8/orbot/releases) selecting universal release because of [https://trac.torproject.org/projects/tor/ticket/26126](https://trac.torproject.org/projects/tor/ticket/26126) . Problem is that the VPN that orbot creates is not used by any app.

I use Resurrection Remix (RR-O-v6.0.0-20180512-klte-Official) based on android 8.1.

Also I installed AFWALL+ allowing only VPN access to apps (not including orbot) and the apps stop having access to internet. For example Firefox stated 'Unable to connect'. Without AFWALL+ filtering, when I visit [check.torproject.org](check.torproject.org) it shows my public IP address.

(Cross-posted from [https://trac.torproject.org/projects/tor/ticket/26140](https://trac.torproject.org/projects/tor/ticket/26140))

**Comment by Pant** [comment]
Same happens for Lineage OS 15.1 (Android 8.1 based). Is there any work done for this?

**Comment by zndrsblurry** [comment]
I encountered this problem when I flashed unofficial lineage OS 16 android pie on my samsung galaxy s5, orbot fails to bootstrap. Before I flashed android pie, everything is working fine with orbot. It seems that orbot has really a bug rather than the OS because when I installed orxy with the add on orxify which uses Tor circuit, everything worked great.

**Comment by n8fr8** [comment]
We've released Orbot 16.3.1 with many important fixes. please test!
