### ISSUE TITLE
[Feature Request] Make a possibility to configure and start a few TOR instances on device

### ISSUE THREAD

**Issue by ghsrcgh** [guardianproject/orbot#176]
Please make a possibility to configure and start a few instances of TOR process on the same phone device (with the same TOR configs at the first step, but with the different ports).

For example, I want to start three different instances on ports :9050, :9150, :9250. In this case I will be able to configure to use Xabber with one TOR-SOCKS, Telegram on the same device with other TOR-SOCKS, and other app - with another TOR-SOCKS.

So, all (many) applications on the same device will have a different IPs and will not be "matched" as one-device-apps (not will be combined by one the same IP-address in/out).

In the current realization all apps that uses TOR have the same IPs, so combined (all accounts/etc). On the PC it is easy to start many different TOR instances, but not on the phone. :(

**Comment by pgerber** [comment]
I generally don't recommend starting multiple instances. For anonymity it's better to have just one instance because an observer will see one connection to an entry guard per Tor instance and it's harder to distinguish streams if everything is multiplex into one connection. Also, on a phone it's going to drain your battery.

If you want multiple socks ports, go to the setting and add a *Custom Torrc* config:

```
SocksPort localhost:9060
SocksPort localhost:9061 IsolateDestAddr
```

This opens two new Socks ports, 9060 and 9061. You can add `IsolateDestAddr` to make sure a different exit node is used for every domain (=example.net sees different IP than for-instance.net). See [Tor's manpage](https://www.torproject.org/docs/tor-manual.html.en#SocksPort) for more details.

By default, SocksPorts are isolated from each other (=different exit IP). From the manpage:

> By default, streams received on different SocksPorts, TransPorts, etc are always isolated from one another.

You could also consider checking *Isolate destination address* in the settings. This will make sure `IsolateDestAddr` is set for the default SocksPort. But then two apps using the same domain would still share an IP address.

**Comment by ghsrcgh** [comment]
Thank you. It seems very interested. I'm not agree about it is better to have one instance (in some cases may be yes, but in some - no), but I (technical guy, who read mans to configure socks) didn't know/skipped about IsolateDestAddr. It seems that it maybe used as you wrote as minimal workaround for my reqeust. Thank you.

I think it will be better to make some FAQ to privacy cases (use cases) where put this answer for users.
