### ISSUE TITLE
Settings crashes in Farsi language

### ISSUE THREAD

**Issue by abdolfazel** [guardianproject/orbot#196]
Hello
When I press settings button in Farsi language the app will crash but it doesn't have problem in English language
Please fix it fast
Thanks

**Comment by bitmold** [comment]
Hi @abdolfazel I'm looking into this now

**Comment by bitmold** [comment]
I am not sure if this crash is related to #207 or potentially for a separate Farsi related settings crash but by addressing the crash in #207 you can open the settings in Farsi. 

@n8fr8 maybe you could clear up some questions I have here:

An unimported `Preference subclass` was used in `xml-fa/preferences.xml` invoked `im.delight.android.languages.LanguagePreference`. By grabbing the `ListPreference` that is used for the any other locale the crash goes away. 

I have made this fix on a branch on my fork [here](https://github.com/bitmold/orbot/tree/farsi_settings_crash_fix). I didn't make a pull request because I couldn't figure out why there is a specific Farsi `preferneces.xml` when all other locales use the default one. I also locally deleted the `Farsi` prefernces.xml and the app appeared to be behaving normally. I saw that the Farsi file has been modified at these two points, but from each commit I couldn't infer why there was a Farsi `prefernces.xml` to begin with:

```
bim@whatever:~/orbot$ git log /home/bim/orbot/app/src/main/res/xml-fa/preferences.xml
commit 93a0092cda4db50d435d8478649afe45799ff863
Author: n8fr8 <nathan@freitas.net>
Date:   Fri May 11 22:53:52 2018 -0400

    update implementation of language selector

commit d21ff80d69b326d004ad3fafb62798808d6d2220
Author: n8fr8 <nathan@freitas.net>
Date:   Thu Jan 4 14:39:40 2018 -0500

    update strings and code for switching Locale in app
```

I wonder if we even need a Farsi `preferences.xml` anymore. If we do, can you please explain why and I'll submit that branch for review.
