### ISSUE TITLE
HTTP Proxy broken in 16.1.0-BETA-2 and newer

### ISSUE THREAD

**Issue by SkewedZeppelin** [guardianproject/orbot#224]
Commit 397391f0580c4997444bfb520fe13c64fa6c973f sets the HTTP proxy port to be dynamic.

For apps that have 8118 hardcoded Tor support is broken.
Even if all apps let the user choose the port it wouldn't matter because anytime Orbot restarted they'd all be broken again until the user manually updated the port again.

Apps on F-Droid that are impacted
```
NetCipher - defaults to 8118?
AntennaPod - allows port selection
Clover - allows port selection
DAVx5 - allows port selection, default 8118
Face Slim - hardcoded to 8118
F-Droid - 'Tor' hardcoded to 8118, but 'other' allows port selection
Lightning Browser - 'Orbot' hardcoded 8118, but 'Custom' allows port selection
OpenKeychain - 'Tor' hardcoded to 8118?, but 'other' allows port selection
Privacy Browser - hardcoded to 8118
RadioDroid - allows port selection
RedReader - hardcoded to 8118
spaRSS - allows port selection
Syncthing - unsure
```

**Comment by n8fr8** [comment]
It is unfortunate these are hardcoded. There is a broadcast event that can be monitored to get the correct port. You can also use the Orbot VPN mode instead of built-in app proxying to route any of these apps through Tor.

That said, we'll consider having it still default to port 8118 if it is available.

We are also adding a settings option to change this to a fixed port in Orbot.

**Comment by SkewedZeppelin** [comment]
814fbb31a58bbcfa4863376354366ac4f974fcd0 seems to work well, thanks!
