### ISSUE TITLE
Implement MOAT as we have done with Onion Browser iOS

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#309]
https://github.com/OnionBrowser/OnionBrowser/issues/124

**Comment by n8fr8** [comment]
You can see in the main activity, how we handle the result of scanning a bridge QR code, and call setNewBridges()

https://github.com/guardianproject/orbot/blob/master/app/src/main/java/org/torproject/android/OrbotMainActivity.java#L925

Getting access to the obfs4proxy binary that is used to run Meek, is a bit more complex. You need to use the TransportManager class as shown here:
https://github.com/guardianproject/orbot/blob/master/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java#L608

More soon

**Comment by bitmold** [comment]
Is anyone actively working on this? I have a lot of time right now and would love to help out with this

**Comment by bitmold** [comment]
There's a way `fetchCaptcha()` in `MoatActivity` can cause the application to crash. 

If a `JsonException` is thrown in the `Response.Listener` for the request being built in that method the exception is caught and this call `displayError(e, response)`. In that method an `AlertDialog` is shown and if the `MoatActivity` is no longer running Orbot will crash. Since the network request happens asynchronously, the the `Context`may not necessarily remain, such as when an `Activity` is in the process of being destroyed. 

There's a really good explanation of this kind of crash here http://dimitar.me/android-displaying-dialogs-from-background-threads/  
```
2020-04-27 00:42:06.073 3877-3877/org.torproject.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.torproject.android, PID: 3877
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@e009c9a is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:907)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:342)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
        at org.torproject.android.ui.onboarding.MoatActivity.displayError(MoatActivity.java:426)
        at org.torproject.android.ui.onboarding.MoatActivity.access$800(MoatActivity.java:60)
        at org.torproject.android.ui.onboarding.MoatActivity$4.onErrorResponse(MoatActivity.java:353)
        at com.android.volley.Request.deliverError(Request.java:617)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

In the posted link this sort of crash seems to be easily avoided by blocking code in `if (!isFinishing()) { ... }`.

**Comment by bitmold** [comment]
Another thing I found testing `MoatActivity` was that each time you rotate a network operation starts via a call to `fetchCaptcha()`

**Comment by bitmold** [comment]
The copy for opening `MoatActivity` is missing.
![image](https://user-images.githubusercontent.com/22125581/80336417-32764280-8825-11ea-8da0-f9c1f3217e88.png)
Personally I also think it would be cool not put MOAT at the bottom of the list either. I think it'd be nice above the web/email "if all else fails" option

**Comment by bitmold** [comment]
When you click the refresh menu item the solution text is cleared only after a new CAPTCHA is downloaded and displayed. I think it would be better to immediately clear the text alongside when the old CAPTCHA disappears and is replaced with a loading indicator

**Comment by bitmold** [comment]
If you don't have an internet connection when the `MoatActivity` is fetching a CAPTCHA the progress bar spins indefinitely and there is no indication to the user

**Comment by bitmold** [comment]
Similarly, if you cut off the internet connection after a CAPTCHA is downloaded the the progress bar will spin indefinitely when you press the "Request Bridges" button

**Comment by bitmold** [comment]
Actually in both of these instances if you wait long enough you get a SOCKS TTL Expired error  
![image](https://user-images.githubusercontent.com/22125581/80338051-6f443880-8829-11ea-953e-242da4dc6234.png)

**Comment by bitmold** [comment]
I noticed that the refresh button is disabled if a network request is in progress. I think this is generally a good idea, but I could see a scenario where a user submits an answer to the CAPTCHA, the request hangs a long time for whatever reason, and the user decides to press the refresh menu item thinking that a new one would load and be frustrated that button is seemingly doing nothing. 

When the refresh menu item is pressed I think it would be a good idea to drop any ongoing requests and request a new CAPTCHA rather than having the button silently be a no op.

**Comment by bitmold** [comment]
After getting an error like the `SocketException` in my previous screenshot. After clicking "Cancel" in the AlertDialog, pressing the refresh menu item to request a new CAPTCHA does nothing since it is disabled. 

The call to `displayError` in this screenshot is from this `Response.ErrorListener` that is directly in the `buildRequest` method:
```
new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        Log.d(MoatActivity.class.getSimpleName(), "Error response.");
                        displayError(error, null);
                    }
                }
```

In this scenario the user is able to resubmit their solution, but is no longer able to request a new CAPTCHA unless they close and reopen the `MoatActivity`

**Comment by bitmold** [comment]
I think that the `AlertDialog` shown in `displayError` should have an "OK"button Instead of a "Cancel" button since when the button gets clicked the dialog is simply closed with nothing getting cancelled

**Comment by bitmold** [comment]
The `EditText` for the CAPTCHA solution is not disabled when the CAPTCHA hasn't loaded yet. 

It's also enabled where I think it should be disabled after the user submits their solution to the CAPTHCA and the network request to the "check" endpoint is still ongoing.

**Comment by tladesignz** [comment]
@bitmold, thanks for all these insights! In fact, some of these were also my thinking. We just talked about it and I will follow up, one by one.
Also #324 will cover some of it.

**Comment by n8fr8** [comment]
@bitmold since @tladesignz implemented all of this for Onion Browser on iOS, he is bringing his knowledge of what was done there over to Orbot, so we can have our UX/UI in sync.

**Comment by tladesignz** [comment]
@bitmold 

> In the posted link this sort of crash seems to be easily avoided by blocking code in `if (!isFinishing()) { ... }`.

Thanks for that catch!

> Another thing I found testing MoatActivity was that each time you rotate the device a network operation starts via a call to fetchCaptcha()
> 
> Edit: this is only the case when a CAPTCHA has not been downloaded and displayed yet

True. Because the activity is gone when the response returns, so there's no place to hand that image to. So I need to restart the request. Or do I overlook something here? How can we achieve to catch the response of the first activity instance in a second activity instance?

> Actually in both of these instances if you wait long enough you get a SOCKS TTL Expired error

Yeah, unfortunately, the MOAT service is awfully slow.

> I noticed that the refresh button is disabled if a network request is in progress. 

Yeah, and Android doesn't visualize this. That's bad. I switched to hiding instead of disabling.

> In this scenario the user is able to resubmit their solution, but is no longer able to request a new CAPTCHA unless they close and reopen the MoatActivity

Again: Thanks for catching this!

> I think that the AlertDialog shown in displayError should have an "OK"button Instead of a "Cancel" button since when the button gets clicked the dialog is simply closed with nothing getting cancelled

True!

> The EditText for the CAPTCHA solution is not disabled when the CAPTCHA hasn't loaded yet.

> It's also enabled where I think it should be disabled after the user submits their solution to the CAPTHCA and the network request to the "check" endpoint is still ongoing.

Ok.

**Comment by bitmold** [comment]
Awesome :+) I'm really excited about this feature. 

> Yeah, unfortunately, the MOAT service is awfully slow.
That's a bummer :( I think it would be nice to indicate this to the user somehow, maybe something like "this may take a minute" or something on the screen. It seems like `/check` is a lot faster than `/fetch` so maybe just when the CAPTCHA is being fetched?
