### ISSUE TITLE
Orbot 16.2.0-BETA-3 tor-0.4.2.7 won't stop when VPN mode is on

### ISSUE THREAD

**Issue by n1m1** [guardianproject/orbot#329]
As per title.

If I push the stop button Orbot gets stuck in "TorService is shutting down". The logs just reports INFO about channelpadding. 

However, this is not a huge problem. As a workaround, if I disable VPN mode and then push the stop button again, TorService shutdowns properly (the logs report "Orbot is deactivated").

I am running Orbot on Android 10, Pixel 3a, GrapheneOS.

**Comment by n8fr8** [comment]
https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by n1m1** [comment]
Hi thanks for notifying. Apparently 16.2.0-RC-1.tor-0.4.2.7 release does not fix the problem. I did a fresh install but Orbot still gets stuck in "TorService is shutting down" when I push the stop button. However the above mentioned workaround still works.

**Comment by bitmold** [comment]
In `OrbotMainActivity` there's this code which tells the service to stop Tor. 

```
    private void stopTor() {
//        requestTorStatus();
        Intent intent = new Intent(this, OrbotService.class);
        stopService(intent);
    }
```

When the VPN is not running the call to `stopService(intent)` fires off the `onDestroy()` method in `OrbotService` but when the VPN is running `onDestroy()` is never called causing the application to hang at stopping Tor. 

The reason for this is that `OrbotVpnManager` uses a `ParcelFileDescriptor` as an interface for Tun2Socks. Android's `VPNService` (which `OrbotService` derives from) will refuse to stop with outstanding interfaces open like that. This is why, as @n1m1 points out, when you disable the VPN before stopping tor, Orbot actually stops as intended since the interface was manually closed.
