### ISSUE TITLE
couldn't find "libtun2socks.so"

### ISSUE THREAD

**Issue by SArsalanK** [guardianproject/orbot#349]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.torproject.android-cZJbhATcrxLYmUMzKYZYVQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-cZJbhATcrxLYmUMzKYZYVQ==/lib/arm, /data/app/org.torproject.android-cZJbhATcrxLYmUMzKYZYVQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libtun2socks.so"

![Screen Shot 2020-06-07 at 3 39 07 AM](https://user-images.githubusercontent.com/2125947/83955804-7589f380-a870-11ea-8a63-265cbb174326.png)

**Comment by bitmold** [comment]
This is because Orbot has both Java code and C code and both need to be compiled in order to run the app. When you build through Android Studio, the java files are compiled, but the underlying C code that runs natively on your Android device is not. Generally speaking, unless you are changing the C code or updates are released to it, you don't need to recompile it and most of the time people hacking on Orbot are just modifying the Java application code.

In order to build the C code you need the Android Native Development Kit (NDK). 

You can follow this guide to install it on your system: https://developer.android.com/studio/projects/install-ndk 

After installing NDK, run these two commands from the root folder of orbot

```
git submodule update --init --recursive
cd orbotservice/src/main
```

The first command downloads all of the external dependencies that Orbot uses, and the second navigates you to the directory where you will build the C code. 

Then, depending on where you installed NDK stuff, you need to run the command `ndk-build` in that directory. For me, it looks something like this since it's installed in my home directory:

```
~/Android/Sdk/ndk/21.0.6113669/ndk-build
```

If it is successful, you should see something like this: 

```
...
...
10 warnings generated.
[x86_64] Compile        : ancillary <= fd_recv.c
[x86_64] Compile        : ancillary <= fd_send.c
[x86_64] StaticLibrary  : libancillary.a
[x86_64] SharedLibrary  : libtun2socks.so
[x86_64] Install        : libtun2socks.so => libs/x86_64/libtun2socks.so
```

After that, you can build your orbot how you normally would through Android Studio! 

I'm glad you opened this issue, there's a file [`BUILD`](https://github.com/guardianproject/orbot/blob/master/BUILD) in the root folder of the repository but the instructions are a bit out of date. @n8fr8 I think we should update this soon.
