### ISSUE TITLE
Block Internet access until Orbot is up and running with VPN mode enabled

### ISSUE THREAD

**Issue by odiferousmint** [guardianproject/orbot#374]
There is certainly a reasonable demand for blocking Internet access until Orbot is up and running with VPN mode enabled, i.e. Internet should not work when Orbot shuts down for whatever reasons as it would reveal your IP. Would this require root? Hopefully not!

**Comment by bitmold** [comment]
You can achieve this through Android's VPN options although it would block traffic from other legit Tor instances such as Tor Browser Android since that app doesn't route traffic through Orbot's VPN. 

But in any case
![Screenshot_2020-07-29-02-39-15.png](https://user-images.githubusercontent.com/22125581/88765743-f1077300-d144-11ea-82dd-82c616443157.png)

Under Settings App -> Network ->VPN -> Orbot (click gear) and select first "Always-on VPN" and then "Block Connections Without VPN". 

Without tor on in Orbot apps (other than Orbot) will not be able to connect to the Internet + even then they'll only be able to connect if Orbot's VPN switch is turned on and those applications have been selected by the user. 

I haven't tested this option in Android extensively so it's possible that this is not a comprehensive approach although I believe it's at least a step in the direction you are looking for

**Comment by bitmold** [comment]
Note that Orbot will only appear on that screen after you have granted it VPN permissions which only happens once in the app ~ that is to say, after clicking OK on this dialog:

![Screenshot_2020-07-29-02-53-03.png](https://user-images.githubusercontent.com/22125581/88766830-b8689900-d146-11ea-8c17-81188926763d.png)

**Comment by odiferousmint** [comment]
I accepted it and VPN mode is active (I double checked), but under Settings -> More connection settings -> VPN, it says "No VPNs". All I can do is add a VPN here of type PPTP, L2TP, and IPSec. I have no idea why Orbot is not shown, and I have no idea how to get to the first screen if I could even do that. I am using Android 5. :/

**Comment by bitmold** [comment]
I just did some more reading and it seems that this feature was added to Android 7 (API 24+)...

**Comment by odiferousmint** [comment]
Thank you in any case. If I get a newer Android phone I will make sure to remember this. I am not sure what to do otherwise right now. :/

**Comment by odiferousmint** [comment]
Is it possible to block Internet access from the software itself, and does it require to be running in the background, or does it require root?
