### ISSUE TITLE
Please make your app movable to SD card.

### ISSUE THREAD

**Issue by fckwan** [guardianproject/orbot#434]
Please make your app movable to SD card.

http://programmerguru.com/android-tutorial/how-to-create-android-app-with-movable-to-sd-card-feature/

https://developer.android.com/guide/topics/data/install-location

**Comment by bitmold** [comment]
> Your running Service is killed and isn't restarted when external storage is remounted. Applications bound to this service can register for the ACTION_EXTERNAL_APPLICATIONS_AVAILABLE broadcast intent, which notifies all applications that aren't installed on external storage when the applications installed on external storage have become available to the system again. After receiving this broadcast, applications can attempt to bind to your service 

This seems dubious because if external storage is unmounted the Tor connection would get thrown out which would deanonymize users. Further I think an adversary could physically steal someones android device and perhaps without unlocking the phone unmount the external storage by plugging it into a computer and kill an ongoing tor session 

Are you using the universal build of Orbot, because if you are there are smaller ones for each supported CPU architecture.
