### ISSUE TITLE
Rooted devices not supported ?

### ISSUE THREAD

**Issue by freebrowser1** [guardianproject/orbot#460]
This app presumably does not support root. It would be useful to support it so one can use Tor without VPN.

Can that be supported ?

**Comment by n8fr8** [comment]
Orbot started with root support before VPN was possible, but it was removed due to being difficult to maintain across devices and ROMs.

You can use an app like Orwall (not maintained but may still work): https://orwall.org/ or AFWall with special iptables rules: https://blog.torproject.org/mission-impossible-hardening-android-security-and-privacy

Lastly, you can also just use apps that know how to talk to Orbot or TorServices directly, like Tor Browser for Android, or that supports SOCKS or HTTP proxying (port 9050 for localhost SOCKS and port 8118 for localhost HTTP proxy)
