### ISSUE TITLE
Official Repo for Orbot?

### ISSUE THREAD

**Issue by Nutomic** [guardianproject/orbot#52]
Is this the official repository for orbot? The [app page](https://guardianproject.info/apps/orbot/) points to a repo at [gitweb.torproject.org](https://gitweb.torproject.org/orbot.git), where the last commit is over 6 months ago. Additionally, it links to [this issue tracker](https://dev.guardianproject.info/projects/orbot), which seems to be abandoned.

It would be great if you could specify a single place for all code and issues.

Edit: Additionally, there are lots of open issues in [this tracker](https://trac.torproject.org/projects/tor/report/57).

**Comment by eighthave** [comment]
I agree, we really need to consolidate Orbot development in a single place, and turn off the others.  Its been confusing for years.  I think either github or https://gitlab.com/torproject would be good places.  Trac is pretty much unusuable

You can track @n8fr8's work in these three repos:
* https://git.torproject.org/orbot.git
* https://git.torproject.org/n8fr8/orbot.git
* https://github.com/n8fr8/orbot

**Comment by eighthave** [comment]
I do  little work on orbot, my repo is https://github.com/eighthave/orbot.git

**Comment by n8fr8** [comment]
I have pushed my dev_gradle branch to: https://gitweb.torproject.org/orbot.git/log/?h=dev_gradle

I develop on Orbot as much as I can, but sometimes there are other priorities. As it is has been working and stable, and there have been no critical flaws in Tor that required client apps to be redistributed (at least on Android), then we haven't put out a new release. Since the gradle work has taken a lot of time and care, that is what I have been investing in. That said, I agree, we need to consolidate bug tracks and ensure the official repos have more information about where dev efforts are taking place.

**Comment by bitmold** [comment]
`https://github.com/guardianproject/orbot.git` has been the official repo for a minute now, I think this can be closed
