### ISSUE TITLE
Why the official Tor Browser has meek while Orbot doesn't have meek?

### ISSUE THREAD

**Issue by corkia1** [guardianproject/orbot#520]
Why I can't choose meek as bridge?

**Comment by n8fr8** [comment]
We were told Meek was no longer going to be available due to MSFT Azure disabling the domain fronting technology. Meek is also easily overwhelmed by users.

Best to either use Snowflake (which is similar to Meek in may ways), or request new bridges from the Tor Bridge service, using the built in process Orbot now offers.
