### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by martino2002** [guardianproject/orbot#546]
On Orbot about page there is written that "Orbot also has the ability, on rooted device, to send all internet traffic through Tor".
I can't understand how can this feature be activated. Orbot never asked for Superuser rights.

**Comment by bitmold** [comment]
Hi, thanks so much for reporting this. I believe this was reported already in https://github.com/guardianproject/orbot/issues/537 however the fix for it hasn't been released yet. 

![image](https://user-images.githubusercontent.com/22125581/145123231-717d361c-61f8-4777-872e-772c59c718f5.png)

With that said, @n8fr8 it would be worthwhile perhaps to update this blurb to describe Snowflake + VPN functionality

**Comment by n8fr8** [comment]
if you want to use tor with root, you should use the InviZible app instead:
https://github.com/Gedsh/InviZible
