### ISSUE TITLE
Windows Version!?

### ISSUE THREAD

**Issue by rayman3003** [guardianproject/orbot#753]
Is there any possibility to have Orbot (+VPN) for windows too?

**Comment by n8fr8** [comment]
There is the Android subsystem for Windows:
https://learn.microsoft.com/en-us/windows/android/wsa/

You can sideload APks
https://www.windowscentral.com/how-sideload-android-apps-using-wsa-windows-11

I am not sure however if the VPN features of Orbot will work in that environment.

You can also easily run Tor on Windows, and then do this:
1


Best way is to set it via Control Panel:

right click start -> control panel -> internet options -> connections tab -> LAN settings
Check off "Use a proxy server for your LAN..."
Optionally, select "Bypass proxy server for local addresses"
Choose "Advanced"
enter in the IP and port (127.0.0.1 : 9150) in the "Socks" fields, and leave the rest of them blank
Hit OK to save/exit out Test with either browser
Source: https://www.reddit.com/r/techsupport/comments/4j0l35/windows_10_route_all_traffic_through_socks5_proxy/

**Comment by rayman3003** [comment]
> You can sideload APks

I don't have Windows 11. (My Windows is 10)

> You can also easily run Tor on Windows

Tor Browser doesn't work for me. It can't connect. Thats why I asked for a windows version of Torbot;

Bcuz Torbot has a VPN too!

**Comment by rayman3003** [comment]
It is not completed. There is no windows exe version in the release section.

**Comment by anon1111111111111** [comment]
Agree. I thought it was such a lousy answer they gave you.
In old time, answers would be always "why would you want it on windows?" "just use Tor browser" 
Seriously, who wants to load an emulator just for this while other VPN clients (some of them also are open sourced and free) can do it?
I guess they just aren't interested in making it work on windows; therefore, somebody else has to make it work.

By the way, this is not exactly as convenient as on Android, but you can still install OnionFruit + Proxifier in order to do similar things as on Android.
