### ISSUE TITLE
Recommended apps cover the App list

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#886]
Device Redmi 9A, Android 10
The list of default apps covers the list of other apps when trying to choose the apps for the VPN mode. 

![699F2C58-BE36-4ED9-8D64-74C1C5BD0885](https://user-images.githubusercontent.com/28932186/232257420-a2ce017b-4fae-4185-b979-25c0dcb1a914.JPG)

**Comment by bitmold** [comment]
Got it fixed - @n8fr8 in situations like this you can't have multiple gridviews, if the first one overtakes the 2nd the 2nd one will render off screen.

The fix was to put both lists into the same view, and also to make that view capable of listing headers and subheaders in addition to apps. this way it allll scrolls 

[device-2023-04-19-125725.webm](https://user-images.githubusercontent.com/22125581/233147251-2aafd05f-b40f-4a15-9bf2-dc5bbe4b8407.webm)

**Comment by bitmold** [comment]
Also @n8fr8 it's a snitchy browser and overall sucks for privacy but what are your thoughts on suggesting Chrome? since it ships with Android I bet it's the browser the vast majority of people use Orbot or not

**Comment by n8fr8** [comment]
Much better!

We're rethinking how the suggest apps work list will be decided, and what the actual text of the suggestion says.
